# Generated by Django 2.2.10 on 2020-03-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=200)),
                ('item_text', models.CharField(max_length=2500)),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
